services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: telegram_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - db

volumes:
  postgresql_data:
    driver: local
  postgresql_bin:
    driver: local

networks:
  db: